CREATE TABLE medicamento (
	codigo BIGINT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	posologia VARCHAR(50)
);

insert into medicamento (codigo, nome) values (1, 'AAS');
insert into medicamento (codigo, nome) values (2, 'Acetaminofeno');
insert into medicamento (codigo, nome) values (3, 'Ácido valproico');
insert into medicamento (codigo, nome) values (4, 'Adenosina');
insert into medicamento (codigo, nome) values (5, 'Albuterol');
insert into medicamento (codigo, nome) values (6, 'Alteplase');
insert into medicamento (codigo, nome) values (7, 'Amicacina');
insert into medicamento (codigo, nome) values (8, 'Aminofilina');
insert into medicamento (codigo, nome) values (9, 'Amiodarona');
insert into medicamento (codigo, nome) values (10, 'Amitriptilina');
insert into medicamento (codigo, nome) values (11, 'Anlodipino');
insert into medicamento (codigo, nome) values (12, 'Atenolol');
insert into medicamento (codigo, nome) values (13, 'Atropina');
insert into medicamento (codigo, nome) values (14, 'Azitromicina');
insert into medicamento (codigo, nome) values (15, 'Azul de metileno');
insert into medicamento (codigo, nome) values (16, 'Betametasona');
insert into medicamento (codigo, nome) values (17, 'Biperideno');
insert into medicamento (codigo, nome) values (18, 'Captopril');
insert into medicamento (codigo, nome) values (19, 'Carbamazepina');
insert into medicamento (codigo, nome) values (20, 'Carvedilol');
insert into medicamento (codigo, nome) values (21, 'Ceftriaxona');
insert into medicamento (codigo, nome) values (22, 'Cetoprofeno');
insert into medicamento (codigo, nome) values (23, 'Cetorolaco');
insert into medicamento (codigo, nome) values (24, 'Ciclobenzaprima');
insert into medicamento (codigo, nome) values (25, 'Ciprofloxacino');
insert into medicamento (codigo, nome) values (26, 'Cisatracurio');
insert into medicamento (codigo, nome) values (27, 'Citalopram');
insert into medicamento (codigo, nome) values (28, 'Claritromicina');
insert into medicamento (codigo, nome) values (29, 'Clonazepam');
insert into medicamento (codigo, nome) values (30, 'Clonidina');
insert into medicamento (codigo, nome) values (31, 'Clopidogrel');
insert into medicamento (codigo, nome) values (32, 'Cloreto de Potássio');
insert into medicamento (codigo, nome) values (33, 'Cloreto de potássio (drágea)');
insert into medicamento (codigo, nome) values (34, 'Clorpromazina');
insert into medicamento (codigo, nome) values (35, 'Colchicina');
insert into medicamento (codigo, nome) values (36, 'Desmopressina');
insert into medicamento (codigo, nome) values (37, 'Dexametasona');
insert into medicamento (codigo, nome) values (38, 'Dexclorfeniramina');
insert into medicamento (codigo, nome) values (39, 'Diazepam');
insert into medicamento (codigo, nome) values (40, 'Diclofenaco');
insert into medicamento (codigo, nome) values (41, 'Digoxina');
insert into medicamento (codigo, nome) values (42, 'Diltiazem');
insert into medicamento (codigo, nome) values (43, 'Dimenidrinato');
insert into medicamento (codigo, nome) values (44, 'Dinitrato de isossorbida');
insert into medicamento (codigo, nome) values (45, 'Dobutamina');
insert into medicamento (codigo, nome) values (46, 'Dopamina');
insert into medicamento (codigo, nome) values (47, 'Enalapril');
insert into medicamento (codigo, nome) values (48, 'Enoxaparina');
insert into medicamento (codigo, nome) values (49, 'Epinefrina');
insert into medicamento (codigo, nome) values (50, 'Escopolamina');
insert into medicamento (codigo, nome) values (51, 'Espironolactona');
insert into medicamento (codigo, nome) values (52, 'Fenilefrina');
insert into medicamento (codigo, nome) values (53, 'Fenitoína');
insert into medicamento (codigo, nome) values (54, 'Fenobarbital');
insert into medicamento (codigo, nome) values (55, 'Fentanil');
insert into medicamento (codigo, nome) values (56, 'Fentanila');
insert into medicamento (codigo, nome) values (57, 'Fluconazol');
insert into medicamento (codigo, nome) values (58, 'Flumazenil');
insert into medicamento (codigo, nome) values (59, 'Fluoxetina');
insert into medicamento (codigo, nome) values (60, 'Furosemida');
insert into medicamento (codigo, nome) values (61, 'Gentamicina');
insert into medicamento (codigo, nome) values (62, 'Gluconato de Calcio');
insert into medicamento (codigo, nome) values (63, 'Haloperidol');
insert into medicamento (codigo, nome) values (64, 'Heparina');
insert into medicamento (codigo, nome) values (65, 'Hidroclorotiazida');
insert into medicamento (codigo, nome) values (66, 'Hidrocortisona');
insert into medicamento (codigo, nome) values (67, 'Hidroxizina');
insert into medicamento (codigo, nome) values (68, 'Insulina');
insert into medicamento (codigo, nome) values (69, 'Iodeto de potássio');
insert into medicamento (codigo, nome) values (70, 'Isoflurano');
insert into medicamento (codigo, nome) values (71, 'Levofloxacino');
insert into medicamento (codigo, nome) values (72, 'Lidocaina');
insert into medicamento (codigo, nome) values (73, 'Loperamida');
insert into medicamento (codigo, nome) values (74, 'Losartana');
insert into medicamento (codigo, nome) values (75, 'Meropenem');
insert into medicamento (codigo, nome) values (76, 'Metadona');
insert into medicamento (codigo, nome) values (77, 'Metaraminol');
insert into medicamento (codigo, nome) values (78, 'Metildopa');
insert into medicamento (codigo, nome) values (79, 'Metilprednisolona');
insert into medicamento (codigo, nome) values (80, 'Metoclopramida');
insert into medicamento (codigo, nome) values (81, 'Metoprolol');
insert into medicamento (codigo, nome) values (82, 'Metronidazol');
insert into medicamento (codigo, nome) values (83, 'Midazolam');
insert into medicamento (codigo, nome) values (84, 'Monoitrato de isossorbida');
insert into medicamento (codigo, nome) values (85, 'Morfina');
insert into medicamento (codigo, nome) values (86, 'Neomicina');
insert into medicamento (codigo, nome) values (87, 'Neostigmina');
insert into medicamento (codigo, nome) values (88, 'Nimesulida');
insert into medicamento (codigo, nome) values (89, 'Nimodipina');
insert into medicamento (codigo, nome) values (90, 'Nitroglicerina');
insert into medicamento (codigo, nome) values (91, 'Noradrenalina');
insert into medicamento (codigo, nome) values (92, 'Norfloxacino');
insert into medicamento (codigo, nome) values (93, 'Omeprazol');
insert into medicamento (codigo, nome) values (94, 'Ondansetrona');
insert into medicamento (codigo, nome) values (95, 'Ondasetrona');
insert into medicamento (codigo, nome) values (96, 'Pancuronio');
insert into medicamento (codigo, nome) values (97, 'Paracetamol');
insert into medicamento (codigo, nome) values (98, 'Prednisolona');
insert into medicamento (codigo, nome) values (99, 'Prednisona');
insert into medicamento (codigo, nome) values (100, 'Prilocaína');
insert into medicamento (codigo, nome) values (101, 'Prometazina');
insert into medicamento (codigo, nome) values (102, 'Propanolol');
insert into medicamento (codigo, nome) values (103, 'Ranitidina');
insert into medicamento (codigo, nome) values (104, 'Remifentanila');
insert into medicamento (codigo, nome) values (105, 'Risperidona');
insert into medicamento (codigo, nome) values (106, 'Sertralina');
insert into medicamento (codigo, nome) values (107, 'Sevoflurano');
insert into medicamento (codigo, nome) values (108, 'Sinvastatina');
insert into medicamento (codigo, nome) values (109, 'Succinilcolina');
insert into medicamento (codigo, nome) values (110, 'Sulfadiazina');
insert into medicamento (codigo, nome) values (111, 'Sulfametoxazol');
insert into medicamento (codigo, nome) values (112, 'Sulfato de magnesio');
insert into medicamento (codigo, nome) values (113, 'Tiopental');
insert into medicamento (codigo, nome) values (114, 'Tramadol');
insert into medicamento (codigo, nome) values (115, 'Varfarina');
insert into medicamento (codigo, nome) values (116, 'Verapamil');